"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 1.10.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""
import os
from easy_thumbnails.conf import Settings as thumbnail_settings

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!mguv&0g^ghh4gf(kyv0o&&!+e4oz)%0m+7%5lmgg+hev2zti&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '127.0.0.1:8000', 'localhost:8000', '*',]

# -----Email config-----#
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'darpontech@gmail.com'
EMAIL_HOST_PASSWORD = 'ks@D1235*'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# EMAIL_HOST = 'mail.darpontech.com'
# EMAIL_HOST_USER = 'core@darpontech.com'
# EMAIL_HOST_PASSWORD = 'ks@D1235*'
# EMAIL_PORT = 465

# Application definition

INSTALLED_APPS = [
    # Third Party Apps
    'flat_responsive',
    'modeltranslation',

    # Django Related Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Django Additional Apps
    'django.contrib.sitemaps',
    'django.contrib.sites',
    'django.contrib.redirects',


    # -----Installed Apps-----#
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'adminsortable2',
    'ckeditor',
    'ckeditor_uploader',
    'crispy_forms',
    'django_cleanup',
    'django_countries',
    'django_unused_media',
    'easy_select2',
    'easy_thumbnails',
    'geoposition',
    'image_cropping',
    'import_export',
    'rest_framework',
    'widget_tweaks',

    # -----Custom Apps-----#
    'preferences',
    'page',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'darpon.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'darpon.context_processors.darpon_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'darpon.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# local sql connection
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'd_darpon',
#         'USER': 'root',
#         'PASSWORD': '',
#         'HOST': '127.0.0.1',
#         'PORT': '3306',
#     },
#     'OPTIONS': {
#         'init_command': {
#             'SET default_storage_engine=INNODB',
#             "SET sql_mode='STRICT_TRANS_TABLES'"
#         },
#     }
# }

# web sql connection
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'nmail',
#         'USER': 'root',
#         'PASSWORD': 'Nu3X8i98KfGG@',
#         'HOST': 'localhost',
#         'PORT': '3306',
#     },
#     'OPTIONS': {
#         'init_command': {
#             'SET default_storage_engine=INNODB',
#             "SET sql_mode='STRICT_TRANS_TABLES'"
#         },
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
)


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

ACCOUNT_ACTIVATION_DAYS = 7
# Automatically log the user in.
REGISTRATION_AUTO_LOGIN = True

SITE_ID = 1
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static/darpon'),
]

STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static")
# Media files (uploads)
MEDIA_URL = "/media/"

MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), "media/darpon")

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'filters': {
#         'require_debug_false': {
#             '()': 'django.utils.log.RequireDebugFalse'
#         }
#     },
#     'handlers': {
#         'mail_admins': {
#             'level': 'ERROR',
#             'filters': ['require_debug_false'],
#             'class': 'django.utils.log.AdminEmailHandler'
#         }
#     },
#     'loggers': {
#         'django.request': {
#             'handlers': ['mail_admins'],
#             'level': 'ERROR',
#             'propagate': True,
#         },
#     }
# }

# Image cropping thumbnails
CRISPY_TEMPLATE_PACK = 'bootstrap3'

# Ckeditor
CKEDITOR_JQUERY_URL = '//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'
CKEDITOR_UPLOAD_PATH = 'ckeditor/'

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'removePlugins': 'font_names',
        'font_names': '',
        'forcePasteAsPlainText': True,
    },
}

# Cropping
THUMBNAIL_PROCESSORS = (
    'image_cropping.thumbnail_processors.crop_corners',
) + thumbnail_settings.THUMBNAIL_PROCESSORS
THUMBNAIL_SUBDIR = 'thumbs'
IMAGE_CROPPING_JQUERY_URL = 'adminsortable2/js/plugins/admincompat.js'

GEOPOSITION_GOOGLE_MAPS_API_KEY = 'AIzaSyCmI-dUfwiDBQrhpEO2fUkd2xzmyJchsGA'

# Settings for django-bootstrap3
# BOOTSTRAP3 = {
#     'set_required': False,  # For Django <= 1.8 only
#     'error_css_class': 'bootstrap3-error',
#     'required_css_class': 'bootstrap3-required',
#     'javascript_in_head': True,
# }

ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
# ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
LOGIN_REDIRECT_URL = '/'
