# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-17 03:51
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields
import image_cropping.fields
import preferences.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='name')),
                ('fullAddress', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='fullAddress')),
                ('address', geoposition.fields.GeopositionField(blank=True, max_length=42, null=True, verbose_name='address')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True, verbose_name='updated on')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=40, unique=True, verbose_name='email')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True, verbose_name='updated on')),
            ],
            options={
                'ordering': ['email'],
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
        migrations.CreateModel(
            name='Faxs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fax', models.CharField(max_length=40, unique=True, verbose_name='fax')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True, verbose_name='updated on')),
            ],
            options={
                'ordering': ['fax'],
                'verbose_name': 'Fax',
                'verbose_name_plural': 'Faxes',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(max_length=206, unique=True, verbose_name='slug')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True, verbose_name='updated on')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
            },
        ),
        migrations.CreateModel(
            name='PageText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=200, null=True, verbose_name='heading')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='content')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True, verbose_name='updated on')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preferences.Page', verbose_name='Pages')),
            ],
            options={
                'verbose_name': 'Page Text',
                'verbose_name_plural': 'Page Text',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=40, null=True, verbose_name='phone number')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True, verbose_name='updated on')),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Phones',
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True, verbose_name='title')),
                ('note', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='note')),
                ('logo', models.ImageField(upload_to=preferences.models.logo_upload_to, verbose_name='logo')),
                ('logo_cropping', image_cropping.fields.ImageRatioField('logo', '1600x900', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='logo cropping')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True, verbose_name='updated on')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': 'Preference',
                'verbose_name_plural': 'Preferences',
            },
        ),
        migrations.CreateModel(
            name='TelePhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=40, null=True, verbose_name='telephone number')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True, verbose_name='updated on')),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preferences.Preference', verbose_name='Preference')),
            ],
            options={
                'verbose_name': 'TelePhone',
                'verbose_name_plural': 'TelePhones',
            },
        ),
        migrations.AddField(
            model_name='phone',
            name='preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preferences.Preference', verbose_name='Preference'),
        ),
        migrations.AddField(
            model_name='faxs',
            name='preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preferences.Preference', verbose_name='Preference'),
        ),
        migrations.AddField(
            model_name='emails',
            name='preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preferences.Preference', verbose_name='Preference'),
        ),
        migrations.AddField(
            model_name='address',
            name='preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preferences.Preference', verbose_name='Preference'),
        ),
    ]
